# NumPy

In [14]:
import numpy as np

## NumPy Arrays

![vector](./images/python_numpy-vector.png)

*In code, index starts from 0*

An array has two important attributes: 
  - `shape`: a tuple of integers indicating the size of the array in each dimension, eg. `(2, 3)` for a 2D array with 2 rows and 3 columns.
  - `dtype`: data types

In [8]:
# specify the shape
a = np.zeros(4);                print(f"a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4, 2));           print(f"a = {a}, a shape = {a.shape}, a data type = {a.dtype}")


a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
a = [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]], a shape = (4, 2), a data type = float64


In [9]:
# literay values
a = np.array([5, 4, 3]);      print(f"a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = [5 4 3], a shape = (3,), a data type = int64


In [36]:
# using a range function
a = np.arange(1, 10, 2);      print(f"a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = [1 3 5 7 9], a shape = (5,), a data type = int64


In [11]:
# random values
a = np.random.random_sample(4); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4);          print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.random.random_sample(4): a = [0.96813519 0.16676218 0.98034601 0.16542138], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.7338616  0.44403662 0.52616222 0.63758124], a shape = (4,), a data type = float64


### Slicing

Supports slicing like Python lists


In [23]:
a = np.arange(10)
print(f"a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

# from index 2 to 5, not including 5
print(a[2:5])

# all below index 3
print(a[:3])

# all above index 5
print(a[5:])

# all elements
print(a[:])

# all even elements
print(a[::2])

a = [0 1 2 3 4 5 6 7 8 9], a shape = (10,), a data type = int64
[2 3 4]
[0 1 2]
[5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


### Single vector operations

In [24]:
a = np.array([1,2,3,4])
print(f"a             : {a}")

# negate elements of a
b = -a
print(f"b = -a        : {b}")

# sum all elements of a, returns a scalar
b = np.sum(a)
print(f"b = np.sum(a) : {b}")

b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = a**2
print(f"b = a**2      : {b}")

a             : [1 2 3 4]
b = -a        : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a): 2.5
b = a**2      : [ 1  4  9 16]


### Scalar Vector operations

In [25]:
a = np.array([1, 2, 3, 4])

# multiply a by a scalar
b = 5 * a
print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]


### Vector Vector element-wise operations

In [26]:
# add two vectors
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise: {a + b}")

Binary operators work element wise: [0 0 6 8]


In [28]:
# dot product
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
c = np.dot(a, b)
print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ")

NumPy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = () 


GPU's and modern CPU's implement Single Instruction, Multiple Data (SIMD) pipelines allowing multiple operations to be issued in parallel. NumPy makes better use of available data parallelism in the underlying hardware. So its dot operation is much faster than you do it in a `for` loop.

## Matrix

![Matrix indexing](./images/python_numpy-matrix.png)

Matrix is often denoted with a capitol, bold letter such as **X**, `m` is often the number of row and `n` the number of columns

In [33]:
a = np.arange(6)
print(f"a             : {a}")

# reshape is a convenient way to create matrices
# the -1 means "figure out the size of this dimension based on the other dimensions"
b = a.reshape(-1, 2)
print(f"b             : {b}")

print(f"b[2].shape:   {b[2].shape}, b[2]   = {b[2]}, type(b[2])   = {type(b[2])}")

a             : [0 1 2 3 4 5]
b             : [[0 1]
 [2 3]
 [4 5]]
b[2].shape:   (2,), b[2]   = [4 5], type(b[2])   = <class 'numpy.ndarray'>


In [34]:
#vector 2-D slicing operations
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

#access 5 consecutive elements (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

# access all elements
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# access all elements in one row (very common usage)
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
# same as
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")

a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array


In [39]:
# np._c
a = np.arange(0, 5, 1)
np.c_[a, a**2, a**3]

array([[ 0,  0,  0],
       [ 1,  1,  1],
       [ 2,  4,  8],
       [ 3,  9, 27],
       [ 4, 16, 64]])

In [43]:
# np._c
a = np.arange(0, 5, 1)

a = a.reshape(-1, 1)

np.ptp(a, axis=0)

array([4])